import { ProjectItem } from "@/types";

export const PORTFOLIO_DATA: ProjectItem[] = [
  {
    id: "project-1",
    slug: "fintech-saas-dashboard",
    title: "ApexPay Enterprise Financial Dashboard",
    client: "Apex Financial Labs",
    category: "Web Apps",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    ],
    summary: "Built a real-time multi-currency transaction processing dashboard with custom charts, role-based access, and instant CSV export capabilities.",
    challenge: "Apex Financial needed to replace a legacy dashboard that was suffering from 6-second page load times and fragmented transaction data across 4 continents.",
    solution: "MitraTech architected a Next.js 15 app with Supabase real-time subscriptions, virtualized data tables, and client-side caching using React Query.",
    results: [
      { label: "Page Load Speed", value: "< 0.4s" },
      { label: "Daily Active Users", value: "45,000+" },
      { label: "Conversion Lift", value: "+210%" },
    ],
    technologies: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Supabase", "Recharts"],
    liveUrl: "https://apexpay-demo.com",
    featured: true,
    testimonial: {
      quote: "MitraTech delivered a financial dashboard that exceeded our performance expectations. Our clients rave about how fast and responsive the analytics views are.",
      author: "David Vance",
      role: "CTO",
      company: "Apex Financial Labs",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    },
  },
  {
    id: "project-2",
    slug: "luxe-ecommerce-store",
    title: "Verve Luxury Eyewear E-Commerce",
    client: "Verve Apparel Group",
    category: "E-Commerce",
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80",
    ],
    summary: "Designed and developed an immersive Headless Shopify store featuring 3D product previews, instant filter search, and dynamic checkout.",
    challenge: "The brand struggled with high cart abandonment rates on mobile devices due to slow page transitions and cluttered product visual pages.",
    solution: "We engineered a ultra-sleek dark glassmorphic UI, added quick 1-click cart drawer actions, and optimized image compression for mobile devices.",
    results: [
      { label: "Mobile Conversion Rate", value: "+185%" },
      { label: "Average Order Value", value: "+34%" },
      { label: "Lighthouse Score", value: "98/100" },
    ],
    technologies: ["Next.js 15", "Shopify Storefront API", "Tailwind CSS", "Framer Motion", "Vercel"],
    liveUrl: "https://verve-eyewear.demo",
    featured: true,
    testimonial: {
      quote: "The web store designed by MitraTech feels like walking through a high-end luxury boutique. Mobile sales doubled within 30 days of launch.",
      author: "Elena Rostova",
      role: "Brand Director",
      company: "Verve Eyewear",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    },
  },
  {
    id: "project-3",
    slug: "ai-healthtech-platform",
    title: "PulseAI Healthcare Diagnostic Portal",
    client: "Pulse BioLabs",
    category: "Web Apps",
    thumbnail: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    ],
    summary: "HIPAA-compliant web platform integrating AI medical diagnostic summaries, patient record vaults, and automated appointment scheduling.",
    challenge: "Pulse BioLabs needed a secure web application capable of handling sensitive patient records while giving doctors instantaneous AI summaries.",
    solution: "MitraTech built a zero-trust enterprise web app with end-to-end encryption, OpenAI medical API integration, and automated patient notifications.",
    results: [
      { label: "Diagnostic Time Saved", value: "65%" },
      { label: "HIPAA Compliance Rating", value: "100%" },
      { label: "Patient Onboarding Lift", value: "+140%" },
    ],
    technologies: ["React 19", "Node.js", "Express", "PostgreSQL", "Tailwind CSS", "OpenAI API"],
    liveUrl: "https://pulseai-health.demo",
    featured: true,
  },
  {
    id: "project-4",
    slug: "b2b-saas-landing-page",
    title: "CloudVault Enterprise Security Site",
    client: "CloudVault Inc.",
    category: "Website Design",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    ],
    summary: "High-converting corporate website with dark mode glassmorphic UI, interactive ROI calculator, and integrated HubSpot CRM lead routing.",
    challenge: "CloudVault was losing enterprise demo bookings to legacy competitors because their existing website lacked premium visual authority.",
    solution: "We redesigned the site using modern Space Grotesk typography, interactive security feature cards, and strategic call-to-action sections.",
    results: [
      { label: "Demo Request Leads", value: "+320%" },
      { label: "Organic Search Traffic", value: "+190%" },
      { label: "Bounce Rate", value: "-42%" },
    ],
    technologies: ["Next.js 15", "TypeScript", "Tailwind CSS", "Framer Motion", "HubSpot API"],
    liveUrl: "https://cloudvault-sec.demo",
    featured: false,
  },
  {
    id: "project-5",
    slug: "brand-identity-vortex",
    title: "Vortex AI Rebranding & Graphic Kit",
    client: "Vortex Intelligence",
    category: "Branding",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    ],
    summary: "Complete brand visual identity overhaul including dynamic 3D logo design, corporate stationery, pitch deck templates, and social media kits.",
    challenge: "Vortex Intelligence was preparing for a Series A funding round and needed a world-class visual identity that reflected their cutting-edge AI research.",
    solution: "MitraTech created a futuristic visual language featuring neon gradients, geometric logo marks, and comprehensive brand guidelines.",
    results: [
      { label: "Series A Investment", value: "$12M Raised" },
      { label: "Brand Perception Survey", value: "98% Positive" },
    ],
    technologies: ["Figma", "Adobe Illustrator", "Photoshop", "Cinema 4D"],
    featured: false,
  },
  {
    id: "project-6",
    slug: "google-ads-ppc-growth",
    title: "Krypton Health PPC Lead Gen Campaign",
    client: "Krypton Medical Supplies",
    category: "Google Ads",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    ],
    summary: "Scalable Google Search & Remarketing PPC campaign targeting B2B hospital procurement managers across North America.",
    challenge: "Cost per lead had spiked to $240 on existing Google Ads accounts due to inefficient keyword matching and unoptimized landing pages.",
    solution: "We restructured campaigns into high-intent search groups, implemented negative keyword filters, and deployed custom Next.js landing pages.",
    results: [
      { label: "Cost Per Lead (CPA)", value: "-62%" },
      { label: "Monthly B2B Qualified Leads", value: "340+" },
      { label: "Return on Ad Spend (ROAS)", value: "4.8x" },
    ],
    technologies: ["Google Ads", "Google Tag Manager", "GA4", "Custom Landing Pages"],
    featured: false,
  },
];
